# Generated by Django 5.1.2 on 2024-11-18 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='fecita',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
