# Generated by Django 5.1.2 on 2024-11-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_reservacion_fecita'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
