# Generated by Django 5.1.2 on 2024-12-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_reservacion_confirmada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
