# Generated by Django 5.1.2 on 2024-12-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_reservacion_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='ampm',
        ),
    ]
